aws_region            = "us-east-1"
environment           = "dev"
project_name          = "awsdemo"
vpc_cidr              = "10.0.0.0/16"
public_subnet_cidr    = "10.0.1.0/24"
private_subnet_cidr   = "10.0.2.0/24"
ec2_instance_type     = "t3.micro"
allowed_ssh_cidr      = "0.0.0.0/0"   # Change to your IP: x.x.x.x/32
s3_bucket_name_prefix = "demo-data"
